// Generated by tools/generate-manifest.mjs; do not edit.
import { NfsImportManifestEntry } from './types';

export const nfsImportManifest: readonly NfsImportManifestEntry[] = [
  {
    "directive": "NfsAccordion",
    "entryPoint": "ngx-foundation-sites/accordion",
    "selector": "[nfsAccordion]",
    "attribute": "nfsAccordion",
    "hostClass": "accordion"
  },
  {
    "directive": "NfsAccordionItem",
    "entryPoint": "ngx-foundation-sites/accordion",
    "selector": "[nfsAccordionItem]",
    "attribute": "nfsAccordionItem",
    "hostClass": "accordion-item"
  },
  {
    "directive": "NfsAccordionTitle",
    "entryPoint": "ngx-foundation-sites/accordion",
    "selector": "button[nfsAccordionTitle]",
    "attribute": "nfsAccordionTitle",
    "hostClass": "accordion-title"
  },
  {
    "directive": "NfsAccordionContent",
    "entryPoint": "ngx-foundation-sites/accordion",
    "selector": "[nfsAccordionContent]",
    "attribute": "nfsAccordionContent",
    "hostClass": "accordion-content"
  },
  {
    "directive": "NfsButton",
    "entryPoint": "ngx-foundation-sites/button",
    "selector": "button[nfsButton], a[nfsButton]",
    "attribute": "nfsButton",
    "hostClass": "button"
  },
  {
    "directive": "NfsColumn",
    "entryPoint": "ngx-foundation-sites/flex-grid",
    "selector": "[nfsColumn]",
    "attribute": "nfsColumn",
    "hostClass": "columns"
  },
  {
    "directive": "NfsColumn",
    "entryPoint": "ngx-foundation-sites/float-grid",
    "selector": "[nfsColumn]",
    "attribute": "nfsColumn",
    "hostClass": "columns"
  },
  {
    "directive": "NfsSmoothScroll",
    "entryPoint": "ngx-foundation-sites/smooth-scroll",
    "selector": "a[nfsSmoothScroll]",
    "attribute": "nfsSmoothScroll",
    "hostClass": null
  },
  {
    "directive": "NfsAbide",
    "entryPoint": "ngx-foundation-sites/abide",
    "selector": "[nfsAbide]",
    "attribute": "nfsAbide",
    "hostClass": "abide"
  },
  {
    "directive": "NfsAbideAlert",
    "entryPoint": "ngx-foundation-sites/abide-alert",
    "selector": "[nfsAbideAlert]",
    "attribute": "nfsAbideAlert",
    "hostClass": "abide-alert"
  },
  {
    "directive": "NfsAbideInput",
    "entryPoint": "ngx-foundation-sites/abide-input",
    "selector": "[nfsAbideInput]",
    "attribute": "nfsAbideInput",
    "hostClass": "abide-input"
  },
  {
    "directive": "NfsAbideLabel",
    "entryPoint": "ngx-foundation-sites/abide-label",
    "selector": "[nfsAbideLabel]",
    "attribute": "nfsAbideLabel",
    "hostClass": "abide-label"
  },
  {
    "directive": "NfsAccordionLazyContent",
    "entryPoint": "ngx-foundation-sites/accordion-lazy-content",
    "selector": "[nfsAccordionLazyContent]",
    "attribute": "nfsAccordionLazyContent",
    "hostClass": "accordion-lazy-content"
  },
  {
    "directive": "NfsAccordionMenu",
    "entryPoint": "ngx-foundation-sites/accordion-menu",
    "selector": "[nfsAccordionMenu]",
    "attribute": "nfsAccordionMenu",
    "hostClass": "accordion-menu"
  },
  {
    "directive": "NfsArrow",
    "entryPoint": "ngx-foundation-sites/arrow",
    "selector": "[nfsArrow]",
    "attribute": "nfsArrow",
    "hostClass": "arrow"
  },
  {
    "directive": "NfsBadge",
    "entryPoint": "ngx-foundation-sites/badge",
    "selector": "[nfsBadge]",
    "attribute": "nfsBadge",
    "hostClass": "badge"
  },
  {
    "directive": "NfsBorderBox",
    "entryPoint": "ngx-foundation-sites/border-box",
    "selector": "[nfsBorderBox]",
    "attribute": "nfsBorderBox",
    "hostClass": "border-box"
  },
  {
    "directive": "NfsBordered",
    "entryPoint": "ngx-foundation-sites/bordered",
    "selector": "[nfsBordered]",
    "attribute": "nfsBordered",
    "hostClass": "bordered"
  },
  {
    "directive": "NfsBorderNone",
    "entryPoint": "ngx-foundation-sites/border-none",
    "selector": "[nfsBorderNone]",
    "attribute": "nfsBorderNone",
    "hostClass": "border-none"
  },
  {
    "directive": "NfsBreadcrumbs",
    "entryPoint": "ngx-foundation-sites/breadcrumbs",
    "selector": "[nfsBreadcrumbs]",
    "attribute": "nfsBreadcrumbs",
    "hostClass": "breadcrumbs"
  },
  {
    "directive": "NfsBreadcrumbsItem",
    "entryPoint": "ngx-foundation-sites/breadcrumbs-item",
    "selector": "[nfsBreadcrumbsItem]",
    "attribute": "nfsBreadcrumbsItem",
    "hostClass": "breadcrumbs-item"
  },
  {
    "directive": "NfsButtonGroup",
    "entryPoint": "ngx-foundation-sites/button-group",
    "selector": "[nfsButtonGroup]",
    "attribute": "nfsButtonGroup",
    "hostClass": "button-group"
  },
  {
    "directive": "NfsCallout",
    "entryPoint": "ngx-foundation-sites/callout",
    "selector": "[nfsCallout]",
    "attribute": "nfsCallout",
    "hostClass": "callout"
  },
  {
    "directive": "NfsCard",
    "entryPoint": "ngx-foundation-sites/card",
    "selector": "[nfsCard]",
    "attribute": "nfsCard",
    "hostClass": "card"
  },
  {
    "directive": "NfsCardDivider",
    "entryPoint": "ngx-foundation-sites/card-divider",
    "selector": "[nfsCardDivider]",
    "attribute": "nfsCardDivider",
    "hostClass": "card-divider"
  },
  {
    "directive": "NfsCardImage",
    "entryPoint": "ngx-foundation-sites/card-image",
    "selector": "[nfsCardImage]",
    "attribute": "nfsCardImage",
    "hostClass": "card-image"
  },
  {
    "directive": "NfsCardSection",
    "entryPoint": "ngx-foundation-sites/card-section",
    "selector": "[nfsCardSection]",
    "attribute": "nfsCardSection",
    "hostClass": "card-section"
  },
  {
    "directive": "NfsCell",
    "entryPoint": "ngx-foundation-sites/cell",
    "selector": "[nfsCell]",
    "attribute": "nfsCell",
    "hostClass": "cell"
  },
  {
    "directive": "NfsCiteBlock",
    "entryPoint": "ngx-foundation-sites/cite-block",
    "selector": "[nfsCiteBlock]",
    "attribute": "nfsCiteBlock",
    "hostClass": "cite-block"
  },
  {
    "directive": "NfsClearfix",
    "entryPoint": "ngx-foundation-sites/clearfix",
    "selector": "[nfsClearfix]",
    "attribute": "nfsClearfix",
    "hostClass": "clearfix"
  },
  {
    "directive": "NfsClose",
    "entryPoint": "ngx-foundation-sites/close",
    "selector": "[nfsClose]",
    "attribute": "nfsClose",
    "hostClass": "close"
  },
  {
    "directive": "NfsCloseButton",
    "entryPoint": "ngx-foundation-sites/close-button",
    "selector": "[nfsCloseButton]",
    "attribute": "nfsCloseButton",
    "hostClass": "close-button"
  },
  {
    "directive": "NfsCloseResult",
    "entryPoint": "ngx-foundation-sites/close-result",
    "selector": "[nfsCloseResult]",
    "attribute": "nfsCloseResult",
    "hostClass": "close-result"
  },
  {
    "directive": "NfsCodeBlock",
    "entryPoint": "ngx-foundation-sites/code-block",
    "selector": "[nfsCodeBlock]",
    "attribute": "nfsCodeBlock",
    "hostClass": "code-block"
  },
  {
    "directive": "NfsCodeInline",
    "entryPoint": "ngx-foundation-sites/code-inline",
    "selector": "[nfsCodeInline]",
    "attribute": "nfsCodeInline",
    "hostClass": "code-inline"
  },
  {
    "directive": "NfsDisplay",
    "entryPoint": "ngx-foundation-sites/display",
    "selector": "[nfsDisplay]",
    "attribute": "nfsDisplay",
    "hostClass": "display"
  },
  {
    "directive": "NfsDrilldown",
    "entryPoint": "ngx-foundation-sites/drilldown",
    "selector": "[nfsDrilldown]",
    "attribute": "nfsDrilldown",
    "hostClass": "drilldown"
  },
  {
    "directive": "NfsDrilldownBack",
    "entryPoint": "ngx-foundation-sites/drilldown-back",
    "selector": "[nfsDrilldownBack]",
    "attribute": "nfsDrilldownBack",
    "hostClass": "drilldown-back"
  },
  {
    "directive": "NfsDrilldownWrapper",
    "entryPoint": "ngx-foundation-sites/drilldown-wrapper",
    "selector": "[nfsDrilldownWrapper]",
    "attribute": "nfsDrilldownWrapper",
    "hostClass": "drilldown-wrapper"
  },
  {
    "directive": "NfsDropdownMenu",
    "entryPoint": "ngx-foundation-sites/dropdown-menu",
    "selector": "[nfsDropdownMenu]",
    "attribute": "nfsDropdownMenu",
    "hostClass": "dropdown-menu"
  },
  {
    "directive": "NfsDropdownPane",
    "entryPoint": "ngx-foundation-sites/dropdown-pane",
    "selector": "[nfsDropdownPane]",
    "attribute": "nfsDropdownPane",
    "hostClass": "dropdown-pane"
  },
  {
    "directive": "NfsEqualizer",
    "entryPoint": "ngx-foundation-sites/equalizer",
    "selector": "[nfsEqualizer]",
    "attribute": "nfsEqualizer",
    "hostClass": "equalizer"
  },
  {
    "directive": "NfsEqualizerWatch",
    "entryPoint": "ngx-foundation-sites/equalizer-watch",
    "selector": "[nfsEqualizerWatch]",
    "attribute": "nfsEqualizerWatch",
    "hostClass": "equalizer-watch"
  },
  {
    "directive": "NfsFieldset",
    "entryPoint": "ngx-foundation-sites/fieldset",
    "selector": "[nfsFieldset]",
    "attribute": "nfsFieldset",
    "hostClass": "fieldset"
  },
  {
    "directive": "NfsFlexAlign",
    "entryPoint": "ngx-foundation-sites/flex-align",
    "selector": "[nfsFlexAlign]",
    "attribute": "nfsFlexAlign",
    "hostClass": "flex-align"
  },
  {
    "directive": "NfsFlexChild",
    "entryPoint": "ngx-foundation-sites/flex-child",
    "selector": "[nfsFlexChild]",
    "attribute": "nfsFlexChild",
    "hostClass": "flex-child"
  },
  {
    "directive": "NfsFlexContainer",
    "entryPoint": "ngx-foundation-sites/flex-container",
    "selector": "[nfsFlexContainer]",
    "attribute": "nfsFlexContainer",
    "hostClass": "flex-container"
  },
  {
    "directive": "NfsFloat",
    "entryPoint": "ngx-foundation-sites/float",
    "selector": "[nfsFloat]",
    "attribute": "nfsFloat",
    "hostClass": "float"
  },
  {
    "directive": "NfsFontBold",
    "entryPoint": "ngx-foundation-sites/font-bold",
    "selector": "[nfsFontBold]",
    "attribute": "nfsFontBold",
    "hostClass": "font-bold"
  },
  {
    "directive": "NfsFontItalic",
    "entryPoint": "ngx-foundation-sites/font-italic",
    "selector": "[nfsFontItalic]",
    "attribute": "nfsFontItalic",
    "hostClass": "font-italic"
  },
  {
    "directive": "NfsFontNormal",
    "entryPoint": "ngx-foundation-sites/font-normal",
    "selector": "[nfsFontNormal]",
    "attribute": "nfsFontNormal",
    "hostClass": "font-normal"
  },
  {
    "directive": "NfsFontWide",
    "entryPoint": "ngx-foundation-sites/font-wide",
    "selector": "[nfsFontWide]",
    "attribute": "nfsFontWide",
    "hostClass": "font-wide"
  },
  {
    "directive": "NfsFormError",
    "entryPoint": "ngx-foundation-sites/form-error",
    "selector": "[nfsFormError]",
    "attribute": "nfsFormError",
    "hostClass": "form-error"
  },
  {
    "directive": "NfsFormLabel",
    "entryPoint": "ngx-foundation-sites/form-label",
    "selector": "[nfsFormLabel]",
    "attribute": "nfsFormLabel",
    "hostClass": "form-label"
  },
  {
    "directive": "NfsGridContainer",
    "entryPoint": "ngx-foundation-sites/grid-container",
    "selector": "[nfsGridContainer]",
    "attribute": "nfsGridContainer",
    "hostClass": "grid-container"
  },
  {
    "directive": "NfsGridX",
    "entryPoint": "ngx-foundation-sites/grid-x",
    "selector": "[nfsGridX]",
    "attribute": "nfsGridX",
    "hostClass": "grid-x"
  },
  {
    "directive": "NfsGridY",
    "entryPoint": "ngx-foundation-sites/grid-y",
    "selector": "[nfsGridY]",
    "attribute": "nfsGridY",
    "hostClass": "grid-y"
  },
  {
    "directive": "NfsHeadingSize",
    "entryPoint": "ngx-foundation-sites/heading-size",
    "selector": "[nfsHeadingSize]",
    "attribute": "nfsHeadingSize",
    "hostClass": "heading-size"
  },
  {
    "directive": "NfsHeight",
    "entryPoint": "ngx-foundation-sites/height",
    "selector": "[nfsHeight]",
    "attribute": "nfsHeight",
    "hostClass": "height"
  },
  {
    "directive": "NfsHelpText",
    "entryPoint": "ngx-foundation-sites/help-text",
    "selector": "[nfsHelpText]",
    "attribute": "nfsHelpText",
    "hostClass": "help-text"
  },
  {
    "directive": "NfsInput",
    "entryPoint": "ngx-foundation-sites/input",
    "selector": "[nfsInput]",
    "attribute": "nfsInput",
    "hostClass": "input"
  },
  {
    "directive": "NfsInputGroup",
    "entryPoint": "ngx-foundation-sites/input-group",
    "selector": "[nfsInputGroup]",
    "attribute": "nfsInputGroup",
    "hostClass": "input-group"
  },
  {
    "directive": "NfsInputGroupButton",
    "entryPoint": "ngx-foundation-sites/input-group-button",
    "selector": "[nfsInputGroupButton]",
    "attribute": "nfsInputGroupButton",
    "hostClass": "input-group-button"
  },
  {
    "directive": "NfsInputGroupField",
    "entryPoint": "ngx-foundation-sites/input-group-field",
    "selector": "[nfsInputGroupField]",
    "attribute": "nfsInputGroupField",
    "hostClass": "input-group-field"
  },
  {
    "directive": "NfsInputGroupLabel",
    "entryPoint": "ngx-foundation-sites/input-group-label",
    "selector": "[nfsInputGroupLabel]",
    "attribute": "nfsInputGroupLabel",
    "hostClass": "input-group-label"
  },
  {
    "directive": "NfsInterchange",
    "entryPoint": "ngx-foundation-sites/interchange",
    "selector": "[nfsInterchange]",
    "attribute": "nfsInterchange",
    "hostClass": "interchange"
  },
  {
    "directive": "NfsLabel",
    "entryPoint": "ngx-foundation-sites/label",
    "selector": "[nfsLabel]",
    "attribute": "nfsLabel",
    "hostClass": "label"
  },
  {
    "directive": "NfsLead",
    "entryPoint": "ngx-foundation-sites/lead",
    "selector": "[nfsLead]",
    "attribute": "nfsLead",
    "hostClass": "lead"
  },
  {
    "directive": "NfsListStyleType",
    "entryPoint": "ngx-foundation-sites/list-style-type",
    "selector": "[nfsListStyleType]",
    "attribute": "nfsListStyleType",
    "hostClass": "list-style-type"
  },
  {
    "directive": "NfsMagellan",
    "entryPoint": "ngx-foundation-sites/magellan",
    "selector": "[nfsMagellan]",
    "attribute": "nfsMagellan",
    "hostClass": "magellan"
  },
  {
    "directive": "NfsMagellanTarget",
    "entryPoint": "ngx-foundation-sites/magellan-target",
    "selector": "[nfsMagellanTarget]",
    "attribute": "nfsMagellanTarget",
    "hostClass": "magellan-target"
  },
  {
    "directive": "NfsMargin",
    "entryPoint": "ngx-foundation-sites/margin",
    "selector": "[nfsMargin]",
    "attribute": "nfsMargin",
    "hostClass": "margin"
  },
  {
    "directive": "NfsMarginTop",
    "entryPoint": "ngx-foundation-sites/margin-top",
    "selector": "[nfsMarginTop]",
    "attribute": "nfsMarginTop",
    "hostClass": "margin-top"
  },
  {
    "directive": "NfsMediaObject",
    "entryPoint": "ngx-foundation-sites/media-object",
    "selector": "[nfsMediaObject]",
    "attribute": "nfsMediaObject",
    "hostClass": "media-object"
  },
  {
    "directive": "NfsMediaObjectSection",
    "entryPoint": "ngx-foundation-sites/media-object-section",
    "selector": "[nfsMediaObjectSection]",
    "attribute": "nfsMediaObjectSection",
    "hostClass": "media-object-section"
  },
  {
    "directive": "NfsMenu",
    "entryPoint": "ngx-foundation-sites/menu",
    "selector": "[nfsMenu]",
    "attribute": "nfsMenu",
    "hostClass": "menu"
  },
  {
    "directive": "NfsMenuIcon",
    "entryPoint": "ngx-foundation-sites/menu-icon",
    "selector": "[nfsMenuIcon]",
    "attribute": "nfsMenuIcon",
    "hostClass": "menu-icon"
  },
  {
    "directive": "NfsMenuItem",
    "entryPoint": "ngx-foundation-sites/menu-item",
    "selector": "[nfsMenuItem]",
    "attribute": "nfsMenuItem",
    "hostClass": "menu-item"
  },
  {
    "directive": "NfsMenuText",
    "entryPoint": "ngx-foundation-sites/menu-text",
    "selector": "[nfsMenuText]",
    "attribute": "nfsMenuText",
    "hostClass": "menu-text"
  },
  {
    "directive": "NfsMeter",
    "entryPoint": "ngx-foundation-sites/meter",
    "selector": "[nfsMeter]",
    "attribute": "nfsMeter",
    "hostClass": "meter"
  },
  {
    "directive": "NfsNoBullet",
    "entryPoint": "ngx-foundation-sites/no-bullet",
    "selector": "[nfsNoBullet]",
    "attribute": "nfsNoBullet",
    "hostClass": "no-bullet"
  },
  {
    "directive": "NfsOffCanvas",
    "entryPoint": "ngx-foundation-sites/off-canvas",
    "selector": "[nfsOffCanvas]",
    "attribute": "nfsOffCanvas",
    "hostClass": "off-canvas"
  },
  {
    "directive": "NfsOffCanvasAbsolute",
    "entryPoint": "ngx-foundation-sites/off-canvas-absolute",
    "selector": "[nfsOffCanvasAbsolute]",
    "attribute": "nfsOffCanvasAbsolute",
    "hostClass": "off-canvas-absolute"
  },
  {
    "directive": "NfsOffCanvasContent",
    "entryPoint": "ngx-foundation-sites/off-canvas-content",
    "selector": "[nfsOffCanvasContent]",
    "attribute": "nfsOffCanvasContent",
    "hostClass": "off-canvas-content"
  },
  {
    "directive": "NfsOffCanvasOverlay",
    "entryPoint": "ngx-foundation-sites/off-canvas-overlay",
    "selector": "[nfsOffCanvasOverlay]",
    "attribute": "nfsOffCanvasOverlay",
    "hostClass": "off-canvas-overlay"
  },
  {
    "directive": "NfsOffCanvasWrapper",
    "entryPoint": "ngx-foundation-sites/off-canvas-wrapper",
    "selector": "[nfsOffCanvasWrapper]",
    "attribute": "nfsOffCanvasWrapper",
    "hostClass": "off-canvas-wrapper"
  },
  {
    "directive": "NfsOpen",
    "entryPoint": "ngx-foundation-sites/open",
    "selector": "[nfsOpen]",
    "attribute": "nfsOpen",
    "hostClass": "open"
  },
  {
    "directive": "NfsOrbit",
    "entryPoint": "ngx-foundation-sites/orbit",
    "selector": "[nfsOrbit]",
    "attribute": "nfsOrbit",
    "hostClass": "orbit"
  },
  {
    "directive": "NfsOrbitBullet",
    "entryPoint": "ngx-foundation-sites/orbit-bullet",
    "selector": "[nfsOrbitBullet]",
    "attribute": "nfsOrbitBullet",
    "hostClass": "orbit-bullet"
  },
  {
    "directive": "NfsOrbitBullets",
    "entryPoint": "ngx-foundation-sites/orbit-bullets",
    "selector": "[nfsOrbitBullets]",
    "attribute": "nfsOrbitBullets",
    "hostClass": "orbit-bullets"
  },
  {
    "directive": "NfsOrbitCaption",
    "entryPoint": "ngx-foundation-sites/orbit-caption",
    "selector": "[nfsOrbitCaption]",
    "attribute": "nfsOrbitCaption",
    "hostClass": "orbit-caption"
  },
  {
    "directive": "NfsOrbitContainer",
    "entryPoint": "ngx-foundation-sites/orbit-container",
    "selector": "[nfsOrbitContainer]",
    "attribute": "nfsOrbitContainer",
    "hostClass": "orbit-container"
  },
  {
    "directive": "NfsOrbitControls",
    "entryPoint": "ngx-foundation-sites/orbit-controls",
    "selector": "[nfsOrbitControls]",
    "attribute": "nfsOrbitControls",
    "hostClass": "orbit-controls"
  },
  {
    "directive": "NfsOrbitFigure",
    "entryPoint": "ngx-foundation-sites/orbit-figure",
    "selector": "[nfsOrbitFigure]",
    "attribute": "nfsOrbitFigure",
    "hostClass": "orbit-figure"
  },
  {
    "directive": "NfsOrbitImage",
    "entryPoint": "ngx-foundation-sites/orbit-image",
    "selector": "[nfsOrbitImage]",
    "attribute": "nfsOrbitImage",
    "hostClass": "orbit-image"
  },
  {
    "directive": "NfsOrbitNext",
    "entryPoint": "ngx-foundation-sites/orbit-next",
    "selector": "[nfsOrbitNext]",
    "attribute": "nfsOrbitNext",
    "hostClass": "orbit-next"
  },
  {
    "directive": "NfsOrbitPrevious",
    "entryPoint": "ngx-foundation-sites/orbit-previous",
    "selector": "[nfsOrbitPrevious]",
    "attribute": "nfsOrbitPrevious",
    "hostClass": "orbit-previous"
  },
  {
    "directive": "NfsOrbitRotation",
    "entryPoint": "ngx-foundation-sites/orbit-rotation",
    "selector": "[nfsOrbitRotation]",
    "attribute": "nfsOrbitRotation",
    "hostClass": "orbit-rotation"
  },
  {
    "directive": "NfsOrbitSlide",
    "entryPoint": "ngx-foundation-sites/orbit-slide",
    "selector": "[nfsOrbitSlide]",
    "attribute": "nfsOrbitSlide",
    "hostClass": "orbit-slide"
  },
  {
    "directive": "NfsOrbitWrapper",
    "entryPoint": "ngx-foundation-sites/orbit-wrapper",
    "selector": "[nfsOrbitWrapper]",
    "attribute": "nfsOrbitWrapper",
    "hostClass": "orbit-wrapper"
  },
  {
    "directive": "NfsOverflow",
    "entryPoint": "ngx-foundation-sites/overflow",
    "selector": "[nfsOverflow]",
    "attribute": "nfsOverflow",
    "hostClass": "overflow"
  },
  {
    "directive": "NfsOverflowX",
    "entryPoint": "ngx-foundation-sites/overflow-x",
    "selector": "[nfsOverflowX]",
    "attribute": "nfsOverflowX",
    "hostClass": "overflow-x"
  },
  {
    "directive": "NfsOverflowY",
    "entryPoint": "ngx-foundation-sites/overflow-y",
    "selector": "[nfsOverflowY]",
    "attribute": "nfsOverflowY",
    "hostClass": "overflow-y"
  },
  {
    "directive": "NfsPadding",
    "entryPoint": "ngx-foundation-sites/padding",
    "selector": "[nfsPadding]",
    "attribute": "nfsPadding",
    "hostClass": "padding"
  },
  {
    "directive": "NfsPaddingVertical",
    "entryPoint": "ngx-foundation-sites/padding-vertical",
    "selector": "[nfsPaddingVertical]",
    "attribute": "nfsPaddingVertical",
    "hostClass": "padding-vertical"
  },
  {
    "directive": "NfsPagination",
    "entryPoint": "ngx-foundation-sites/pagination",
    "selector": "[nfsPagination]",
    "attribute": "nfsPagination",
    "hostClass": "pagination"
  },
  {
    "directive": "NfsPaginationEllipsis",
    "entryPoint": "ngx-foundation-sites/pagination-ellipsis",
    "selector": "[nfsPaginationEllipsis]",
    "attribute": "nfsPaginationEllipsis",
    "hostClass": "pagination-ellipsis"
  },
  {
    "directive": "NfsPaginationNext",
    "entryPoint": "ngx-foundation-sites/pagination-next",
    "selector": "[nfsPaginationNext]",
    "attribute": "nfsPaginationNext",
    "hostClass": "pagination-next"
  },
  {
    "directive": "NfsPaginationPrevious",
    "entryPoint": "ngx-foundation-sites/pagination-previous",
    "selector": "[nfsPaginationPrevious]",
    "attribute": "nfsPaginationPrevious",
    "hostClass": "pagination-previous"
  },
  {
    "directive": "NfsPosition",
    "entryPoint": "ngx-foundation-sites/position",
    "selector": "[nfsPosition]",
    "attribute": "nfsPosition",
    "hostClass": "position"
  },
  {
    "directive": "NfsPrintBreakInside",
    "entryPoint": "ngx-foundation-sites/print-break-inside",
    "selector": "[nfsPrintBreakInside]",
    "attribute": "nfsPrintBreakInside",
    "hostClass": "print-break-inside"
  },
  {
    "directive": "NfsProgress",
    "entryPoint": "ngx-foundation-sites/progress",
    "selector": "[nfsProgress]",
    "attribute": "nfsProgress",
    "hostClass": "progress"
  },
  {
    "directive": "NfsProgressElement",
    "entryPoint": "ngx-foundation-sites/progress-element",
    "selector": "[nfsProgressElement]",
    "attribute": "nfsProgressElement",
    "hostClass": "progress-element"
  },
  {
    "directive": "NfsProgressMeter",
    "entryPoint": "ngx-foundation-sites/progress-meter",
    "selector": "[nfsProgressMeter]",
    "attribute": "nfsProgressMeter",
    "hostClass": "progress-meter"
  },
  {
    "directive": "NfsProgressMeterText",
    "entryPoint": "ngx-foundation-sites/progress-meter-text",
    "selector": "[nfsProgressMeterText]",
    "attribute": "nfsProgressMeterText",
    "hostClass": "progress-meter-text"
  },
  {
    "directive": "NfsRadius",
    "entryPoint": "ngx-foundation-sites/radius",
    "selector": "[nfsRadius]",
    "attribute": "nfsRadius",
    "hostClass": "radius"
  },
  {
    "directive": "NfsResponsiveAccordionTabsPanel",
    "entryPoint": "ngx-foundation-sites/responsive-accordion-tabs-panel",
    "selector": "[nfsResponsiveAccordionTabsPanel]",
    "attribute": "nfsResponsiveAccordionTabsPanel",
    "hostClass": "responsive-accordion-tabs-panel"
  },
  {
    "directive": "NfsResponsiveEmbed",
    "entryPoint": "ngx-foundation-sites/responsive-embed",
    "selector": "[nfsResponsiveEmbed]",
    "attribute": "nfsResponsiveEmbed",
    "hostClass": "responsive-embed"
  },
  {
    "directive": "NfsResponsiveMenu",
    "entryPoint": "ngx-foundation-sites/responsive-menu",
    "selector": "[nfsResponsiveMenu]",
    "attribute": "nfsResponsiveMenu",
    "hostClass": "responsive-menu"
  },
  {
    "directive": "NfsResponsiveToggle",
    "entryPoint": "ngx-foundation-sites/responsive-toggle",
    "selector": "[nfsResponsiveToggle]",
    "attribute": "nfsResponsiveToggle",
    "hostClass": "responsive-toggle"
  },
  {
    "directive": "NfsResponsiveToggleMenu",
    "entryPoint": "ngx-foundation-sites/responsive-toggle-menu",
    "selector": "[nfsResponsiveToggleMenu]",
    "attribute": "nfsResponsiveToggleMenu",
    "hostClass": "responsive-toggle-menu"
  },
  {
    "directive": "NfsReveal",
    "entryPoint": "ngx-foundation-sites/reveal",
    "selector": "[nfsReveal]",
    "attribute": "nfsReveal",
    "hostClass": "reveal"
  },
  {
    "directive": "NfsRounded",
    "entryPoint": "ngx-foundation-sites/rounded",
    "selector": "[nfsRounded]",
    "attribute": "nfsRounded",
    "hostClass": "rounded"
  },
  {
    "directive": "NfsRow",
    "entryPoint": "ngx-foundation-sites/row",
    "selector": "[nfsRow]",
    "attribute": "nfsRow",
    "hostClass": "row"
  },
  {
    "directive": "NfsSeparator",
    "entryPoint": "ngx-foundation-sites/separator",
    "selector": "[nfsSeparator]",
    "attribute": "nfsSeparator",
    "hostClass": "separator"
  },
  {
    "directive": "NfsShadow",
    "entryPoint": "ngx-foundation-sites/shadow",
    "selector": "[nfsShadow]",
    "attribute": "nfsShadow",
    "hostClass": "shadow"
  },
  {
    "directive": "NfsShowForSr",
    "entryPoint": "ngx-foundation-sites/show-for-sr",
    "selector": "[nfsShowForSr]",
    "attribute": "nfsShowForSr",
    "hostClass": "show-for-sr"
  },
  {
    "directive": "NfsShowOnFocus",
    "entryPoint": "ngx-foundation-sites/show-on-focus",
    "selector": "[nfsShowOnFocus]",
    "attribute": "nfsShowOnFocus",
    "hostClass": "show-on-focus"
  },
  {
    "directive": "NfsSizing",
    "entryPoint": "ngx-foundation-sites/sizing",
    "selector": "[nfsSizing]",
    "attribute": "nfsSizing",
    "hostClass": "sizing"
  },
  {
    "directive": "NfsSlider",
    "entryPoint": "ngx-foundation-sites/slider",
    "selector": "[nfsSlider]",
    "attribute": "nfsSlider",
    "hostClass": "slider"
  },
  {
    "directive": "NfsSliderFill",
    "entryPoint": "ngx-foundation-sites/slider-fill",
    "selector": "[nfsSliderFill]",
    "attribute": "nfsSliderFill",
    "hostClass": "slider-fill"
  },
  {
    "directive": "NfsSliderHandle",
    "entryPoint": "ngx-foundation-sites/slider-handle",
    "selector": "[nfsSliderHandle]",
    "attribute": "nfsSliderHandle",
    "hostClass": "slider-handle"
  },
  {
    "directive": "NfsStat",
    "entryPoint": "ngx-foundation-sites/stat",
    "selector": "[nfsStat]",
    "attribute": "nfsStat",
    "hostClass": "stat"
  },
  {
    "directive": "NfsSticky",
    "entryPoint": "ngx-foundation-sites/sticky",
    "selector": "[nfsSticky]",
    "attribute": "nfsSticky",
    "hostClass": "sticky"
  },
  {
    "directive": "NfsStickyContainer",
    "entryPoint": "ngx-foundation-sites/sticky-container",
    "selector": "[nfsStickyContainer]",
    "attribute": "nfsStickyContainer",
    "hostClass": "sticky-container"
  },
  {
    "directive": "NfsSubheader",
    "entryPoint": "ngx-foundation-sites/subheader",
    "selector": "[nfsSubheader]",
    "attribute": "nfsSubheader",
    "hostClass": "subheader"
  },
  {
    "directive": "NfsSubmenu",
    "entryPoint": "ngx-foundation-sites/submenu",
    "selector": "[nfsSubmenu]",
    "attribute": "nfsSubmenu",
    "hostClass": "submenu"
  },
  {
    "directive": "NfsSubmenuToggle",
    "entryPoint": "ngx-foundation-sites/submenu-toggle",
    "selector": "[nfsSubmenuToggle]",
    "attribute": "nfsSubmenuToggle",
    "hostClass": "submenu-toggle"
  },
  {
    "directive": "NfsSubmenuToggleText",
    "entryPoint": "ngx-foundation-sites/submenu-toggle-text",
    "selector": "[nfsSubmenuToggleText]",
    "attribute": "nfsSubmenuToggleText",
    "hostClass": "submenu-toggle-text"
  },
  {
    "directive": "NfsSwitch",
    "entryPoint": "ngx-foundation-sites/switch",
    "selector": "[nfsSwitch]",
    "attribute": "nfsSwitch",
    "hostClass": "switch"
  },
  {
    "directive": "NfsSwitchActive",
    "entryPoint": "ngx-foundation-sites/switch-active",
    "selector": "[nfsSwitchActive]",
    "attribute": "nfsSwitchActive",
    "hostClass": "switch-active"
  },
  {
    "directive": "NfsSwitchInactive",
    "entryPoint": "ngx-foundation-sites/switch-inactive",
    "selector": "[nfsSwitchInactive]",
    "attribute": "nfsSwitchInactive",
    "hostClass": "switch-inactive"
  },
  {
    "directive": "NfsSwitchInput",
    "entryPoint": "ngx-foundation-sites/switch-input",
    "selector": "[nfsSwitchInput]",
    "attribute": "nfsSwitchInput",
    "hostClass": "switch-input"
  },
  {
    "directive": "NfsSwitchPaddle",
    "entryPoint": "ngx-foundation-sites/switch-paddle",
    "selector": "[nfsSwitchPaddle]",
    "attribute": "nfsSwitchPaddle",
    "hostClass": "switch-paddle"
  },
  {
    "directive": "NfsTab",
    "entryPoint": "ngx-foundation-sites/tab",
    "selector": "[nfsTab]",
    "attribute": "nfsTab",
    "hostClass": "tab"
  },
  {
    "directive": "NfsTable",
    "entryPoint": "ngx-foundation-sites/table",
    "selector": "[nfsTable]",
    "attribute": "nfsTable",
    "hostClass": "table"
  },
  {
    "directive": "NfsTableScroll",
    "entryPoint": "ngx-foundation-sites/table-scroll",
    "selector": "[nfsTableScroll]",
    "attribute": "nfsTableScroll",
    "hostClass": "table-scroll"
  },
  {
    "directive": "NfsTabs",
    "entryPoint": "ngx-foundation-sites/tabs",
    "selector": "[nfsTabs]",
    "attribute": "nfsTabs",
    "hostClass": "tabs"
  },
  {
    "directive": "NfsTabsContent",
    "entryPoint": "ngx-foundation-sites/tabs-content",
    "selector": "[nfsTabsContent]",
    "attribute": "nfsTabsContent",
    "hostClass": "tabs-content"
  },
  {
    "directive": "NfsTabsGroup",
    "entryPoint": "ngx-foundation-sites/tabs-group",
    "selector": "[nfsTabsGroup]",
    "attribute": "nfsTabsGroup",
    "hostClass": "tabs-group"
  },
  {
    "directive": "NfsTabsLazyContent",
    "entryPoint": "ngx-foundation-sites/tabs-lazy-content",
    "selector": "[nfsTabsLazyContent]",
    "attribute": "nfsTabsLazyContent",
    "hostClass": "tabs-lazy-content"
  },
  {
    "directive": "NfsTabsPanel",
    "entryPoint": "ngx-foundation-sites/tabs-panel",
    "selector": "[nfsTabsPanel]",
    "attribute": "nfsTabsPanel",
    "hostClass": "tabs-panel"
  },
  {
    "directive": "NfsTabsTitle",
    "entryPoint": "ngx-foundation-sites/tabs-title",
    "selector": "[nfsTabsTitle]",
    "attribute": "nfsTabsTitle",
    "hostClass": "tabs-title"
  },
  {
    "directive": "NfsTextAlign",
    "entryPoint": "ngx-foundation-sites/text-align",
    "selector": "[nfsTextAlign]",
    "attribute": "nfsTextAlign",
    "hostClass": "text-align"
  },
  {
    "directive": "NfsTextDecoration",
    "entryPoint": "ngx-foundation-sites/text-decoration",
    "selector": "[nfsTextDecoration]",
    "attribute": "nfsTextDecoration",
    "hostClass": "text-decoration"
  },
  {
    "directive": "NfsTextHide",
    "entryPoint": "ngx-foundation-sites/text-hide",
    "selector": "[nfsTextHide]",
    "attribute": "nfsTextHide",
    "hostClass": "text-hide"
  },
  {
    "directive": "NfsTextNowrap",
    "entryPoint": "ngx-foundation-sites/text-nowrap",
    "selector": "[nfsTextNowrap]",
    "attribute": "nfsTextNowrap",
    "hostClass": "text-nowrap"
  },
  {
    "directive": "NfsTextTransform",
    "entryPoint": "ngx-foundation-sites/text-transform",
    "selector": "[nfsTextTransform]",
    "attribute": "nfsTextTransform",
    "hostClass": "text-transform"
  },
  {
    "directive": "NfsTextTruncate",
    "entryPoint": "ngx-foundation-sites/text-truncate",
    "selector": "[nfsTextTruncate]",
    "attribute": "nfsTextTruncate",
    "hostClass": "text-truncate"
  },
  {
    "directive": "NfsTextWrap",
    "entryPoint": "ngx-foundation-sites/text-wrap",
    "selector": "[nfsTextWrap]",
    "attribute": "nfsTextWrap",
    "hostClass": "text-wrap"
  },
  {
    "directive": "NfsThumbnail",
    "entryPoint": "ngx-foundation-sites/thumbnail",
    "selector": "[nfsThumbnail]",
    "attribute": "nfsThumbnail",
    "hostClass": "thumbnail"
  },
  {
    "directive": "NfsTitleBar",
    "entryPoint": "ngx-foundation-sites/title-bar",
    "selector": "[nfsTitleBar]",
    "attribute": "nfsTitleBar",
    "hostClass": "title-bar"
  },
  {
    "directive": "NfsTitleBarLeft",
    "entryPoint": "ngx-foundation-sites/title-bar-left",
    "selector": "[nfsTitleBarLeft]",
    "attribute": "nfsTitleBarLeft",
    "hostClass": "title-bar-left"
  },
  {
    "directive": "NfsTitleBarRight",
    "entryPoint": "ngx-foundation-sites/title-bar-right",
    "selector": "[nfsTitleBarRight]",
    "attribute": "nfsTitleBarRight",
    "hostClass": "title-bar-right"
  },
  {
    "directive": "NfsTitleBarTitle",
    "entryPoint": "ngx-foundation-sites/title-bar-title",
    "selector": "[nfsTitleBarTitle]",
    "attribute": "nfsTitleBarTitle",
    "hostClass": "title-bar-title"
  },
  {
    "directive": "NfsToggle",
    "entryPoint": "ngx-foundation-sites/toggle",
    "selector": "[nfsToggle]",
    "attribute": "nfsToggle",
    "hostClass": "toggle"
  },
  {
    "directive": "NfsToggler",
    "entryPoint": "ngx-foundation-sites/toggler",
    "selector": "[nfsToggler]",
    "attribute": "nfsToggler",
    "hostClass": "toggler"
  },
  {
    "directive": "NfsTooltip",
    "entryPoint": "ngx-foundation-sites/tooltip",
    "selector": "[nfsTooltip]",
    "attribute": "nfsTooltip",
    "hostClass": "tooltip"
  },
  {
    "directive": "NfsTopBar",
    "entryPoint": "ngx-foundation-sites/top-bar",
    "selector": "[nfsTopBar]",
    "attribute": "nfsTopBar",
    "hostClass": "top-bar"
  },
  {
    "directive": "NfsTopBarLeft",
    "entryPoint": "ngx-foundation-sites/top-bar-left",
    "selector": "[nfsTopBarLeft]",
    "attribute": "nfsTopBarLeft",
    "hostClass": "top-bar-left"
  },
  {
    "directive": "NfsTopBarRight",
    "entryPoint": "ngx-foundation-sites/top-bar-right",
    "selector": "[nfsTopBarRight]",
    "attribute": "nfsTopBarRight",
    "hostClass": "top-bar-right"
  },
  {
    "directive": "NfsTopBarTitle",
    "entryPoint": "ngx-foundation-sites/top-bar-title",
    "selector": "[nfsTopBarTitle]",
    "attribute": "nfsTopBarTitle",
    "hostClass": "top-bar-title"
  },
  {
    "directive": "NfsVisibility",
    "entryPoint": "ngx-foundation-sites/visibility",
    "selector": "[nfsVisibility]",
    "attribute": "nfsVisibility",
    "hostClass": "visibility"
  },
  {
    "directive": "NfsWidth",
    "entryPoint": "ngx-foundation-sites/width",
    "selector": "[nfsWidth]",
    "attribute": "nfsWidth",
    "hostClass": "width"
  }
];
