'use strict';
// PROTOTYPE (ticket 137): the shared core of the Variant declaration tooling, as the
// Variant declaration tooling spec describes it ("API: the shared core"). Throwaway code:
// no tests, minimal error handling. It imports neither nx nor @nx/devkit, so the
// Architect builder runs without them.
const fs = require('node:fs');
const path = require('node:path');
const { pathToFileURL, fileURLToPath } = require('node:url');

const PREFIX = 'ngx-foundation-sites:';
const MODULE = 'ngx-foundation-sites';
const FILE_NAME = 'nfs-variants.d.ts';
const HEADER_START = '// Generated by ngx-foundation-sites';
const manifest = require('./manifest.json');
const libraryVersion = require('../package.json').version;
const bySetting = new Map(manifest.registries.map((r) => [r.setting, r]));
const byName = new Map(manifest.registries.map((r) => [r.registry, r]));

function load(name, fromDirs, who) {
  for (const dir of fromDirs) {
    try {
      return require(require.resolve(name, { paths: [dir] }));
    } catch {
      // try the next location
    }
  }

  throw new Error(
    `${PREFIX} the ${who} needs ${name}. Install it: npm install --save-dev ${name}`,
  );
}

function angularBuildDir(root) {
  try {
    return path.dirname(
      require.resolve('@angular/build/package.json', { paths: [root] }),
    );
  } catch {
    return null;
  }
}

const posix = (p) => p.replace(/\\/g, '/');

// ---------------------------------------------------------------------------
// 1. Sources
// ---------------------------------------------------------------------------

/** Angular's merge: base options, then each named configuration's. */
function mergeTargetOptions(target, configuration) {
  const name = configuration ?? target.defaultConfiguration;
  let options = { ...(target.options ?? {}) };

  for (const c of (name ?? '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean)) {
    options = { ...options, ...(target.configurations?.[c] ?? {}) };
  }

  return { options, configuration: name ?? null };
}

/**
 * Warning M11: configurations of the build target that change the styles. The used
 * configuration counts too: when it overrides styles, every other configuration (the
 * dev server's development configuration, say) builds with different ones.
 */
function styleOverrideWarnings(target, used, buildTarget, file) {
  const warnings = [];

  for (const [name, config] of Object.entries(target.configurations ?? {})) {
    if (
      config &&
      ('styles' in config || 'stylePreprocessorOptions' in config)
    ) {
      warnings.push(
        `${PREFIX} the ${name} configuration of ${buildTarget} changes styles or stylePreprocessorOptions; ${file} follows ${used ? `the ${used} configuration` : 'the base options'}.`,
      );
    }
  }

  return warnings;
}

/** Sources from merged build options: every injected Sass global stylesheet. */
function sourcesFromBuildOptions(options) {
  const styles = (options.styles ?? []).map((s) =>
    typeof s === 'string'
      ? { input: s, inject: true }
      : { input: s.input, inject: s.inject !== false },
  );
  const optimization = options.optimization;
  const optimized =
    optimization === undefined
      ? true
      : typeof optimization === 'object'
        ? !!(typeof optimization.styles === 'object'
            ? (optimization.styles.minify ?? true)
            : (optimization.styles ?? false))
        : !!optimization;

  return {
    stylesheets: styles
      .filter((s) => s.inject && /\.s[ac]ss$/.test(s.input))
      .map((s) => posix(s.input)),
    includePaths: options.stylePreprocessorOptions?.includePaths ?? [],
    optimized,
  };
}

// ---------------------------------------------------------------------------
// 2. Compile (the application builder's resolution, through the same esbuild)
// ---------------------------------------------------------------------------

async function createResolver(root, optimized) {
  const buildDir = angularBuildDir(root);
  const esbuild = load(
    'esbuild',
    [buildDir, root].filter(Boolean),
    'Variant declaration tooling',
  );
  let resolve;
  // The stylesheet bundle options of @angular/build 22.2.0
  // (src/tools/esbuild/stylesheets/bundle-options.js).
  const ctx = await esbuild.context({
    absWorkingDir: root,
    write: false,
    platform: 'browser',
    conditions: [
      'style',
      'sass',
      'less',
      optimized ? 'production' : 'development',
    ],
    mainFields: ['style', 'sass'],
    resolveExtensions: [],
    logLevel: 'silent',
    plugins: [
      {
        name: 'nfs-expose-resolve',
        setup(build) {
          resolve = build.resolve;
        },
      },
    ],
  });

  return {
    resolve: (url, resolveDir) =>
      resolve(url.startsWith('pkg:') ? url.slice(4) : url, {
        kind: 'import-rule',
        resolveDir,
      }),
    dispose: () => ctx.dispose(),
  };
}

// Copied from @angular/build 22.2.0 src/tools/esbuild/stylesheets/sass-language.js.
function isPackageUrl(url) {
  if (url.startsWith('pkg:')) {
    return true;
  }

  return (
    url.length > 0 &&
    !url.startsWith('.') &&
    !url.startsWith('/') &&
    !url.startsWith('\\') &&
    !url.includes(':')
  );
}

function parsePackageName(url) {
  const parts = (url.startsWith('pkg:') ? url.slice(4) : url).split('/');
  const hasScope = parts.length >= 2 && parts[0][0] === '@';
  const [nameOrScope, nameOrFirstPath, ...pathPart] = parts;
  const packageName = hasScope
    ? `${nameOrScope}/${nameOrFirstPath}`
    : nameOrScope;

  return {
    packageName,
    pathSegments:
      !hasScope && nameOrFirstPath ? [nameOrFirstPath, ...pathPart] : pathPart,
  };
}

/**
 * The Sass the application builder loads: @angular/build 22.2.0 compiles with sass-embedded
 * (its dependency, the native Dart compiler) unless NG_BUILD_SASS_EMBEDDED is 0 or false
 * (src/utils/environment-options.js), and with its pure-JS sass dependency otherwise.
 */
function loadSass(root) {
  const buildDir = angularBuildDir(root);
  const dirs = [buildDir, root].filter(Boolean);
  const flag = (process.env.NG_BUILD_SASS_EMBEDDED ?? '').toLowerCase();

  if (flag !== '0' && flag !== 'false') {
    try {
      return {
        sass: load('sass-embedded', dirs, 'Variant declaration tooling'),
        name: 'sass-embedded',
      };
    } catch {
      // fall back to the pure-JS compiler
    }
  }

  return {
    sass: load('sass', dirs, 'Variant declaration tooling'),
    name: 'sass',
  };
}

async function compileSources(root, sources, project) {
  const { sass } = loadSass(root);
  const compiler = await sass.initAsyncCompiler();
  const resolver = await createResolver(root, sources.optimized ?? true);
  const results = [];

  try {
    for (const stylesheet of sources.stylesheets) {
      const started = performance.now();
      const importer = {
        findFileUrl: async (url, options) => {
          const containingPath =
            options.containingUrl?.protocol === 'file:'
              ? fileURLToPath(options.containingUrl)
              : undefined;
          const resolveDir = containingPath
            ? path.dirname(containingPath)
            : root;
          const result = await resolver.resolve(url, resolveDir);

          if (result.path) {
            return pathToFileURL(result.path);
          }

          if (!isPackageUrl(url)) {
            return null;
          }

          const { packageName, pathSegments } = parsePackageName(url);
          const pkg = await resolver.resolve(
            `${packageName}/package.json`,
            resolveDir,
          );

          return pkg.path
            ? pathToFileURL(path.join(path.dirname(pkg.path), ...pathSegments))
            : null;
        },
      };

      try {
        const result = await compiler.compileAsync(
          path.resolve(root, stylesheet),
          {
            style: 'expanded',
            loadPaths: (sources.includePaths ?? []).map((p) =>
              path.resolve(root, p),
            ),
            quietDeps: true,
            logger: sass.Logger.silent,
            importers: [importer],
          },
        );
        results.push({
          stylesheet,
          css: result.css,
          ms: Math.round(performance.now() - started),
          loadedUrls: result.loadedUrls.length,
        });
      } catch (error) {
        throw new Error(
          `${PREFIX} compiling ${stylesheet} for ${project} failed: ${error.message}`,
        );
      }
    }
  } finally {
    await resolver.dispose();
    await compiler.dispose();
  }

  return results;
}

// ---------------------------------------------------------------------------
// 3. Read the Variant properties (the Variant property format)
// ---------------------------------------------------------------------------

function parsePropertyValue(raw) {
  const value = raw.trim();

  if (/^\d+$/.test(value)) {
    return { count: Number(value), raw: value };
  }

  const names = [...new Set(value.split(/[\s,]+/).filter(Boolean))];

  return { names, raw: value };
}

function readProperties(compiled, project) {
  const found = new Map();

  for (const { stylesheet, css } of compiled) {
    const inThisSheet = new Map();

    for (const m of css.matchAll(/(--nfs-[a-z0-9-]+)\s*:([^;}]*)/g)) {
      const property = m[1];

      if (!manifest.registries.some((r) => r.property === property)) {
        continue;
      }

      const value = parsePropertyValue(m[2]);
      const previous = inThisSheet.get(property);

      if (previous && previous.raw !== value.raw) {
        throw new Error(
          `${PREFIX} ${property} is printed twice with different values in ${stylesheet}.`,
        );
      }

      inThisSheet.set(property, value);
    }

    for (const [property, value] of inThisSheet) {
      const other = found.get(property);

      if (
        other &&
        other.value.raw.replace(/[\s,]+/g, ' ') !==
          value.raw.replace(/[\s,]+/g, ' ')
      ) {
        throw new Error(
          `${PREFIX} ${property} lists different names in ${other.stylesheet} and ${stylesheet}; name the one to follow in the nfs-variants target's stylesheets option.`,
        );
      }

      found.set(property, { value, stylesheet });
    }
  }

  if (found.size === 0) {
    throw new Error(
      `${PREFIX} ${compiled.map((c) => c.stylesheet).join(', ')} of ${project} print no Variant properties. Add \`@import 'ngx-foundation-sites';\` after your Foundation imports and include the Library mixins of the families you use (for example \`@include nfs-button;\`), or remove the project's nfs-variants target.`,
    );
  }

  return found;
}

// ---------------------------------------------------------------------------
// 4. Expected model
// ---------------------------------------------------------------------------

function effectiveNames(registry, found) {
  const own = found.get(registry.property);

  if (own) {
    return own.value.names ?? [];
  }

  return registry.base
    ? effectiveNames(bySetting.get(registry.base), found)
    : registry.defaults;
}

function expectedModel(found) {
  const model = new Map();

  for (const registry of manifest.registries) {
    const own = found.get(registry.property);

    if (!own) {
      continue;
    }

    if (registry.kind === 'count') {
      const count = own.value.count;

      if (count === undefined || count > 999) {
        throw new Error(
          `${PREFIX} ${registry.property} is '${own.value.raw}' in ${own.stylesheet}; a count must be a whole number from 0 to 999.`,
        );
      }

      if (count !== registry.count) {
        model.set(registry.registry, { count });
      }

      continue;
    }

    const names = own.value.names ?? [];
    const base = registry.base
      ? effectiveNames(bySetting.get(registry.base), found)
      : registry.defaults;
    const adds = names.filter((n) => !base.includes(n)).sort();
    const removes = base.filter((n) => !names.includes(n));

    if (adds.length || removes.length) {
      model.set(registry.registry, { adds, removes });
    }
  }

  return model;
}

// ---------------------------------------------------------------------------
// 5. Parse an existing declaration file (TypeScript's parser only)
// ---------------------------------------------------------------------------

function parseDeclarationFile(text, fileName, ts) {
  const sf = ts.createSourceFile(fileName, text, ts.ScriptTarget.Latest, true);
  const problems = [];
  const registries = new Map();
  const line = (node) =>
    sf.getLineAndCharacterOfPosition(node.getStart(sf)).line + 1;
  const isModule = sf.statements.some(
    (s) =>
      ts.isImportDeclaration(s) ||
      ts.isImportEqualsDeclaration(s) ||
      ts.isExportDeclaration(s) ||
      ts.isExportAssignment(s) ||
      (ts.canHaveModifiers(s) &&
        ts
          .getModifiers(s)
          ?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword)),
  );
  const generated = text.startsWith(HEADER_START);

  if (!isModule) {
    problems.push({
      id: 'M5',
      text: `${fileName} has no import or export, so its declare module replaces the library's types. Add \`import '${MODULE}';\` as its first statement.`,
    });
  }

  for (const statement of sf.statements) {
    if (
      !ts.isModuleDeclaration(statement) ||
      !ts.isStringLiteral(statement.name) ||
      statement.name.text !== MODULE
    ) {
      if (
        ts.isInterfaceDeclaration(statement) &&
        byName.has(statement.name.text)
      ) {
        problems.push({
          id: 'M7',
          text: `${fileName}:${line(statement)}: ${statement.name.text} is outside declare module '${MODULE}'.`,
        });
      }

      continue;
    }

    for (const member of statement.body?.statements ?? []) {
      if (!ts.isInterfaceDeclaration(member)) {
        continue;
      }

      const name = member.name.text;
      const registry = byName.get(name);

      if (!registry) {
        problems.push({
          id: 'M6',
          text: `${fileName}:${line(member)} declares ${name}, which is not a Variant registry of ${MODULE} ${libraryVersion}.`,
        });
        continue;
      }

      const entry = registries.get(name) ?? {
        open: false,
        names: new Map(),
        count: undefined,
      };
      registries.set(name, entry);

      for (const m of member.members) {
        if (ts.isIndexSignatureDeclaration(m)) {
          entry.open = true;
          continue;
        }

        const bad = () =>
          problems.push({
            id: 'M7',
            text: `${fileName}:${line(m)}: ${name}.${m.name ? m.name.getText(sf) : '?'} must be \`true\`, \`false\`, or (for count registries) \`count: <whole number>\`; quote numeric names ('25': true).`,
          });

        if (
          !ts.isPropertySignature(m) ||
          !m.type ||
          !(ts.isIdentifier(m.name) || ts.isStringLiteral(m.name))
        ) {
          bad();
          continue;
        }

        const key = m.name.text;

        if (registry.kind === 'count') {
          if (
            key === 'count' &&
            ts.isLiteralTypeNode(m.type) &&
            ts.isNumericLiteral(m.type.literal) &&
            /^\d+$/.test(m.type.literal.text)
          ) {
            entry.count = Number(m.type.literal.text);
          } else {
            bad();
          }

          continue;
        }

        if (
          ts.isLiteralTypeNode(m.type) &&
          m.type.literal.kind === ts.SyntaxKind.TrueKeyword
        ) {
          entry.names.set(key, true);
        } else if (
          ts.isLiteralTypeNode(m.type) &&
          m.type.literal.kind === ts.SyntaxKind.FalseKeyword
        ) {
          entry.names.set(key, false);
        } else {
          bad();
        }
      }
    }
  }

  return { generated, isModule, registries, problems };
}

// ---------------------------------------------------------------------------
// 6. Compare by meaning
// ---------------------------------------------------------------------------

function compare(expected, file, found) {
  const drift = [];
  const open = [];

  for (const registry of manifest.registries) {
    const want = expected.get(registry.registry);
    const have = file.registries.get(registry.registry);

    if (have?.open) {
      open.push(registry.registry);
      continue;
    }

    const lines = [];

    if (registry.kind === 'count') {
      const wantCount = want?.count ?? registry.count;
      const haveCount = have?.count ?? registry.count;

      if (wantCount !== haveCount) {
        lines.push(
          `count is ${haveCount} in the file and ${wantCount} in ${registry.property}`,
        );
      }
    } else {
      const wantAdds = want?.adds ?? [];
      const wantRemoves = want?.removes ?? [];
      const haveAdds = [...(have?.names ?? [])]
        .filter(([, v]) => v)
        .map(([k]) => k);
      const haveRemoves = [...(have?.names ?? [])]
        .filter(([, v]) => !v)
        .map(([k]) => k);
      const inProp = found.has(registry.property);

      for (const n of wantAdds.filter((n) => !haveAdds.includes(n))) {
        lines.push(`add ${n}: true (${n} is in ${registry.property})`);
      }

      for (const n of haveAdds.filter((n) => !wantAdds.includes(n))) {
        lines.push(
          `remove ${n}: true (${n} is not in ${inProp ? registry.property : `${registry.property}, which no stylesheet prints`})`,
        );
      }

      for (const n of wantRemoves.filter((n) => !haveRemoves.includes(n))) {
        lines.push(`add ${n}: false (${n} is not in ${registry.property})`);
      }

      for (const n of haveRemoves.filter((n) => !wantRemoves.includes(n))) {
        lines.push(
          `remove ${n}: false (${n} is in ${registry.property} again)`,
        );
      }
    }

    if (lines.length) {
      drift.push({ registry: registry.registry, lines });
    }
  }

  return { drift, open };
}

// ---------------------------------------------------------------------------
// 7. Render and format
// ---------------------------------------------------------------------------

const key = (n) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(n) ? n : `'${n}'`);

function command(workspaceKind, project) {
  return workspaceKind === 'nx'
    ? `\`nx sync\` or \`nx run ${project}:nfs-variants\``
    : `\`ng run ${project}:nfs-variants\``;
}

function render(expected, sources, workspaceKind, project) {
  const names = [...expected.keys()].sort();
  const blocks = names.map((name) => {
    const entry = expected.get(name);
    const members =
      entry.count !== undefined
        ? [`    count: ${entry.count};`]
        : [
            ...entry.adds.map((n) => `    ${key(n)}: true;`),
            ...entry.removes.map((n) => `    ${key(n)}: false;`),
          ];

    return `  interface ${name} {\n${members.join('\n')}\n  }`;
  });
  const body = blocks.length
    ? `declare module '${MODULE}' {\n${blocks.join('\n')}\n}`
    : `declare module '${MODULE}' {}`;

  // The empty global augmentation makes TypeScript's builder treat a change to this file as
  // affecting every file (isFileAffectingGlobalScope), so a running dev server re-checks
  // every template after each rewrite (ticket 137, question 1).
  return [
    `${HEADER_START} from ${sources.join(', ')}. Do not edit; run ${command(workspaceKind, project)} to update it.`,
    `import '${MODULE}';`,
    '',
    body,
    '',
    '// Makes a running dev server re-check templates after every change to this file.',
    'declare global {}',
    '',
  ].join('\n');
}

async function format(text, absoluteFile, root) {
  let prettier;

  try {
    prettier = require(require.resolve('prettier', { paths: [root] }));
  } catch {
    return text;
  }

  const info = await prettier.getFileInfo(absoluteFile, {
    ignorePath: path.join(root, '.prettierignore'),
  });

  if (info.ignored) {
    return text;
  }

  const config = (await prettier.resolveConfig(absoluteFile)) ?? {};

  return prettier.format(text, { ...config, filepath: absoluteFile });
}

// ---------------------------------------------------------------------------
// One project, end to end. readFile(workspaceRelativePath) returns text or null.
// ---------------------------------------------------------------------------

async function processProject({
  root,
  project,
  workspaceKind,
  file,
  sources,
  readFile,
  warnings = [],
}) {
  const ts = load('typescript', [root], 'Variant declaration tooling');
  const compiled = await compileSources(root, sources, project);
  const found = readProperties(compiled, project);
  const expected = expectedModel(found);
  const sourceList = compiled.map((c) => c.stylesheet);
  const current = readFile(file);
  const timing = compiled
    .map((c) => `${c.stylesheet} ${c.ms} ms, ${c.loadedUrls} files`)
    .join('; ');
  const properties = Object.fromEntries(
    [...found].map(([p, v]) => [p, v.value.raw]),
  );

  if (current === null) {
    const content = await format(
      render(expected, sourceList, workspaceKind, project),
      path.join(root, file),
      root,
    );

    return {
      status: 'write',
      file,
      content,
      drift: [{ registry: '(file)', lines: ['the file does not exist'] }],
      sourceList,
      timing,
      properties,
      warnings,
    };
  }

  const model = parseDeclarationFile(current, file, ts);

  if (model.problems.length) {
    return {
      status: 'problem',
      file,
      problems: model.problems,
      sourceList,
      timing,
      properties,
      warnings,
    };
  }

  const { drift, open } = compare(expected, model, found);

  if (!drift.length) {
    return {
      status: 'in-step',
      file,
      drift,
      open,
      sourceList,
      timing,
      properties,
      warnings,
    };
  }

  if (!model.generated) {
    return {
      status: 'hand-written-drift',
      file,
      drift,
      sourceList,
      timing,
      properties,
      warnings,
    };
  }

  const content = await format(
    render(expected, sourceList, workspaceKind, project),
    path.join(root, file),
    root,
  );

  return {
    status: 'write',
    file,
    content,
    drift,
    sourceList,
    timing,
    properties,
    warnings,
  };
}

function driftSummary(drift) {
  return drift.map((d) => `${d.registry}: ${d.lines.join('; ')}`).join('; ');
}

/** M2 (check failure), M4 (hand-written drift), M5 to M7 (problems). */
function failureMessage(result, workspaceKind, project) {
  if (result.status === 'problem') {
    return result.problems.map((p) => `${PREFIX} ${p.text}`).join('\n');
  }

  const lines = result.drift.flatMap((d) =>
    d.lines.map((l) => `  ${d.registry}: ${l}`),
  );

  if (result.status === 'hand-written-drift') {
    return [
      `${PREFIX} ${result.file} was not generated by ngx-foundation-sites, so it is not rewritten. Make these edits:`,
      ...lines,
      'or delete it to let the tooling write it.',
    ].join('\n');
  }

  return [
    `${PREFIX} ${result.file} no longer matches ${result.sourceList.join(', ')}:`,
    ...lines,
    `Run ${command(workspaceKind, project)} to update it.`,
  ].join('\n');
}

module.exports = {
  PREFIX,
  FILE_NAME,
  HEADER_START,
  manifest,
  mergeTargetOptions,
  styleOverrideWarnings,
  sourcesFromBuildOptions,
  compileSources,
  readProperties,
  expectedModel,
  parseDeclarationFile,
  compare,
  render,
  format,
  processProject,
  driftSummary,
  failureMessage,
  command,
  posix,
};
