// CONSUMER FILE (a generator could write it): family name -> lazily loaded carrier.
import { NfsFamilyCarriers } from '../lib/family-styles';

export const carriers: NfsFamilyCarriers = {
  'forms': () => import('./forms'),
  'range-input': () => import('./range-input'),
  'progress-element': () => import('./progress-element'),
  'meter-element': () => import('./meter-element'),
  'button': () => import('./button'),
  'button-group': () => import('./button-group'),
  'close-button': () => import('./close-button'),
  'label': () => import('./label'),
  'progress-bar': () => import('./progress-bar'),
  'slider': () => import('./slider'),
  'switch': () => import('./switch'),
  'table': () => import('./table'),
  'badge': () => import('./badge'),
  'breadcrumbs': () => import('./breadcrumbs'),
  'callout': () => import('./callout'),
  'card': () => import('./card'),
  'dropdown': () => import('./dropdown'),
  'pagination': () => import('./pagination'),
  'tooltip': () => import('./tooltip'),
  'accordion': () => import('./accordion'),
  'media-object': () => import('./media-object'),
  'orbit': () => import('./orbit'),
  'responsive-embed': () => import('./responsive-embed'),
  'tabs': () => import('./tabs'),
  'thumbnail': () => import('./thumbnail'),
  'menu': () => import('./menu'),
  'menu-icon': () => import('./menu-icon'),
  'accordion-menu': () => import('./accordion-menu'),
  'drilldown-menu': () => import('./drilldown-menu'),
  'dropdown-menu': () => import('./dropdown-menu'),
  'off-canvas': () => import('./off-canvas'),
  'reveal': () => import('./reveal'),
  'sticky': () => import('./sticky'),
  'title-bar': () => import('./title-bar'),
  'top-bar': () => import('./top-bar'),
};
